wealthkernel/api-documentation-guides

docs/Welcome.md, docs/balances/Basics.md, docs/balances/FAQs.md, toc.json
https://wealthkernel.stoplight.io/docs/guides/branches/feature%2Fbalances/ZG9jOjYzMzI0-welcome
=> WK2-147: Add Balances API guides

docs/Welcome.md, docs/deposits/Basics.md, docs/deposits/FAQs.md, toc.json
Add a guide to how portfolios are funded as we get a lot of questions around this from new tenants.
https://wealthkernel.stoplight.io/docs/guides/branches/deposits/ZG9jOjQzNTA5NTQ4-basics
=> Deposits Guides

docs/webhooks/FAQs.md
User story: https://wealthkernel.atlassian.net/browse/WK2-273
=> WK2-273 update FAQs

docs/webhooks/FAQs.md, docs/webhooks/Getting-Started.md, docs/webhooks/Secrets.md, docs/webhooks/Testing.md
https://wealthkernel.atlassian.net/browse/WK2-288
=> WK2-288 Update Webhooks guides as closed beta

docs/webhooks/Secrets.md
https://wealthkernel.atlassian.net/browse/WK2-287
=> WK2-287 change webhooks secret TTL to a year

docs/isa-subscriptions/Basics.md
=> Wk2 438 isa sandbox warning

docs/isa-subscriptions/Basics.md
https://wealthkernel.atlassian.net/browse/WK2-439
=> Modified docs/isa-subscriptions/Basics.md

docs/Welcome.md, docs/inbound-transfers/Basics.md, docs/inbound-transfers/ISA-Transfers.md, docs/inbound-transfers/Sandbox-Simulation.md, toc.json
Added following guides:
- Basics for inbound transfers
- ISA transfers requirements
- Sandbox Simulation
=> Added inbound transfers guides

docs/sandbox/Sandbox-FAQ.md
=> WK2-943 Added information about fee process in prod/sandbox

docs/deposits/Basics.md, docs/withdrawals/Basics.md, docs/withdrawals/FAQs.md
- [Y] I have spellchecked my changes.
- [N/A] I have updated the API Documentation CHANGELOG where applicable.
- [N/A] I have added my guides to Welcome.md where applicable
- [N/A] I have added my guides to toc.json where applicable.
=> Default bank account definition

docs/accounts/Basics.md
=> Update account basics to include information around due diligence

docs/Welcome.md, docs/accounts/Sandbox-Simulation.md, docs/sandbox/Sandbox-FAQ.md, toc.json
=> Account activation delay

docs/deposits/FAQs.md
----
[Preview](https://wealthkernel.stoplight.io/docs/guides/branches/additional-deposit-not-matched-reasons/6dd37b0861218-deposit-fa-qs)
=> Add additional reasons for why a deposit has not matched

docs/accounts/Opening-Requirements.md
=> Add additional account requirements to guide

docs/Welcome.md, docs/direct-debits/How-To-Request-Payments.md
=> Fixed links on welcome page.  Rm'd 2 days to create a mandate

docs/direct-debits/How-To-Request-Payments.md
=> DD payment Min and Max limits are mentioned.

docs/Welcome.md, docs/accounts/Basics.md, docs/accounts/Sandbox-Simulation.md, docs/inbound-transfers/Basics.md, docs/portfolios/Basics.md, docs/transactions/Basics.md, docs/withdrawals/Basics.md, toc.json
=> Portfolios

docs/accounts/Opening-Requirements.md
=> Add opening requirements for a corporate GIA

docs/Welcome.md, docs/isa-declarations/Basics.md, docs/isa-declarations/FAQs.md, toc.json
=> Modified 3 files

.github/pull_request_template.md
=> remove checkboxes from pr template

docs/transactions/Basics.md
=> fix code block navigation issue

docs/portfolios/Basics.md
=> Added single product mandate to the portfolios basics

docs/balances/FAQs.md, docs/webhooks/Event-Types.md, docs/webhooks/Testing.md
=> Balances faq update

docs/bank-accounts/Basics.md, docs/bank-accounts/FAQs.md, docs/direct-debits/How-To-Request-Payments.md, toc.json
=> Add information around bank accounts and their lifecycle

docs/inbound-transfers/Basics.md
=> Add webhooks for inbound transfer to guide

docs/Welcome.md, docs/bank-accounts/Sandbox-Simulation.md, toc.json
=> Bank accounts sandbox simulation | WK1-1743

docs/performance/Basics.md
=> tweak net performance warning

docs/performance/Basics.md
=> Update dividends section, remove price changes for simpler examples

docs/portfolios/Basics.md
=> Added portfolio webhooks

docs/performance/Basics.md
=> Corrected fees example calculation for Day n+1

docs/deposits/FAQs.md
=> Add FAQ about canceling stale deposit expectations

docs/direct-debits/UI-Guidelines.md
=> WK2-1544 Amend DD joint account mandate text

docs/deposits/FAQs.md
=> remove duplicate deposit as reason for not matching

docs/Welcome.md
=> rework API basics list

docs/accounts/Basics.md, docs/balances/FAQs.md, docs/deposits/Basics.md, docs/deposits/FAQs.md, docs/direct-debits/Timings.md, docs/sandbox/Sandbox-FAQ.md
=> fix link to portfolios

docs/sipp-illustrations/Sandbox-simulation.md
=> Added docs/sipp-illustrations/Sandbox-simulation.md

docs/outbound-transfers/Basics.md, docs/outbound-transfers/Sandbox-Simulation.md, toc.json
=> Add guides for outbound transfer

docs/accounts/Opening-Requirements.md
=> Chris lovell modified opening requirements

docs/bank-accounts/Basics.md, docs/bank-accounts/Sandbox-Simulation.md
=> WK1-2273 BIC/IBAN bank accounts

docs/cash-savings/Interest.md, toc.json
=> WK2-1852 How interest is paid

docs/Welcome.md, toc.json
=> Rework guides welcome page

docs/valuations/Basics.md, docs/valuations/FAQs.md, toc.json
=> WK2-1923 Add valuations guide
